# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/17138/Desktop/Sirius/Programming/BookstoreSystem

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/17138/Desktop/Sirius/Programming/BookstoreSystem

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/17138/Desktop/Sirius/Programming/BookstoreSystem/CMakeFiles /mnt/c/Users/17138/Desktop/Sirius/Programming/BookstoreSystem/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/17138/Desktop/Sirius/Programming/BookstoreSystem/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named code

# Build rule for target.
code: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 code
.PHONY : code

# fast build rule for target.
code/fast:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/build
.PHONY : code/fast

src/DataOperation.o: src/DataOperation.cpp.o

.PHONY : src/DataOperation.o

# target to build an object file
src/DataOperation.cpp.o:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/DataOperation.cpp.o
.PHONY : src/DataOperation.cpp.o

src/DataOperation.i: src/DataOperation.cpp.i

.PHONY : src/DataOperation.i

# target to preprocess a source file
src/DataOperation.cpp.i:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/DataOperation.cpp.i
.PHONY : src/DataOperation.cpp.i

src/DataOperation.s: src/DataOperation.cpp.s

.PHONY : src/DataOperation.s

# target to generate assembly for a file
src/DataOperation.cpp.s:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/DataOperation.cpp.s
.PHONY : src/DataOperation.cpp.s

src/HashTable.o: src/HashTable.cpp.o

.PHONY : src/HashTable.o

# target to build an object file
src/HashTable.cpp.o:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/HashTable.cpp.o
.PHONY : src/HashTable.cpp.o

src/HashTable.i: src/HashTable.cpp.i

.PHONY : src/HashTable.i

# target to preprocess a source file
src/HashTable.cpp.i:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/HashTable.cpp.i
.PHONY : src/HashTable.cpp.i

src/HashTable.s: src/HashTable.cpp.s

.PHONY : src/HashTable.s

# target to generate assembly for a file
src/HashTable.cpp.s:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/HashTable.cpp.s
.PHONY : src/HashTable.cpp.s

src/UserManager.o: src/UserManager.cpp.o

.PHONY : src/UserManager.o

# target to build an object file
src/UserManager.cpp.o:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/UserManager.cpp.o
.PHONY : src/UserManager.cpp.o

src/UserManager.i: src/UserManager.cpp.i

.PHONY : src/UserManager.i

# target to preprocess a source file
src/UserManager.cpp.i:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/UserManager.cpp.i
.PHONY : src/UserManager.cpp.i

src/UserManager.s: src/UserManager.cpp.s

.PHONY : src/UserManager.s

# target to generate assembly for a file
src/UserManager.cpp.s:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/UserManager.cpp.s
.PHONY : src/UserManager.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... code"
	@echo "... src/DataOperation.o"
	@echo "... src/DataOperation.i"
	@echo "... src/DataOperation.s"
	@echo "... src/HashTable.o"
	@echo "... src/HashTable.i"
	@echo "... src/HashTable.s"
	@echo "... src/UserManager.o"
	@echo "... src/UserManager.i"
	@echo "... src/UserManager.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

